#!/bin/bash

direction=`cat config.txt`

node timer.js $1 $direction

osascript Timer.scpt

afplay /System/Library/Sounds/Glass.aiff

sleep 1

defaultMessage="The timer is up, take a break\!"
storedMessage=`cat message.txt`
message=""

if [ -z "$storedMessage" ];
then
    message=$defaultMessage
else
    message=$storedMessage
fi

echo $message

say $message